# Generated by Django 2.0.1 on 2018-02-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=20)),
                ('aircraft_regNum', models.CharField(max_length=10)),
                ('aircraft_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=30)),
                ('airport_country', models.CharField(max_length=30)),
                ('airport_timeZone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=10)),
                ('booked_seats', models.PositiveIntegerField()),
                ('booking_status', models.CharField(choices=[(1, 'ONHOLD'), (2, 'CONFIRMED'), (3, 'CANCELLED'), (4, 'TRAVELLED')], default='ONHOLD', max_length=9)),
                ('booking_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('aircraft_seats', models.PositiveIntegerField()),
                ('depart_dateTime', models.DateTimeField()),
                ('arrive_dateTime', models.DateTimeField()),
                ('flight_duration', models.TimeField()),
                ('seat_price', models.PositiveIntegerField()),
                ('depart_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.Airport')),
                ('dest_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='flights.Airport')),
                ('flight_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_airline_num', models.CharField(max_length=10)),
                ('invoice_provider_num', models.CharField(max_length=10)),
                ('invoice_status', models.BooleanField()),
                ('invoice_stamp', models.CharField(max_length=10)),
                ('invocie_book_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.Booking')),
                ('invoice_amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_firstName', models.CharField(max_length=20)),
                ('passenger_surname', models.CharField(max_length=20)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=30)),
                ('provider_address', models.URLField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ManyToManyField(to='flights.Passenger'),
        ),
    ]
