# Generated by Django 2.0.1 on 2018-02-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_airline_num',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_provider_num',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_stamp',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
