# Generated by Django 2.0.1 on 2018-02-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180222_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft_seats',
        ),
    ]
