# Generated by Django 2.0.1 on 2018-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20180222_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('ONHOLD', 'ONHOLD'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('TRAVELLED', 'TRAVELLED')], default='ONHOLD', max_length=9),
        ),
    ]
