# Generated by Django 2.0.1 on 2018-02-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20180222_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='airline_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='airline_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
