# Generated by Django 2.0.1 on 2018-03-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20180228_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='depart_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_airport',
            field=models.ManyToManyField(related_name='departure', to='flights.Airport'),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='dest_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='dest_airport',
            field=models.ManyToManyField(related_name='destination', to='flights.Airport'),
        ),
    ]
