# Generated by Django 2.0.1 on 2018-03-05 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_flight_is_flex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_duration',
            field=models.DurationField(default=datetime.timedelta(0, 1200)),
        ),
    ]
