# Generated by Django 2.0.1 on 2018-03-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20180305_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='is_flex',
        ),
    ]
