# Generated by Django 2.0.1 on 2018-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_remove_invoice_invoice_airline_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_stamp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
