# Generated by Django 2.0.1 on 2018-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_auto_20180319_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_stamp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
