# Generated by Django 2.0.1 on 2018-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_auto_20180319_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invocie_book_num',
            new_name='invoice_book_num',
        ),
    ]
