# Generated by Django 2.0.1 on 2018-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_auto_20180320_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.BooleanField(default=False),
        ),
    ]
