# Generated by Django 2.0.1 on 2018-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_auto_20180320_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_provider_num',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
