# Generated by Django 2.0.1 on 2018-03-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_auto_20180320_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='depart_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.Airport'),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='dest_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='dest_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='flights.Airport'),
        ),
    ]
