# Generated by Django 2.0.1 on 2018-03-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_auto_20180321_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='depart_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dest_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='flights.Airport'),
        ),
    ]
